version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
        environment:
          NPM_CONFIG_COLOR: false
          NPM_CONFIG_LOGLEVEL: warn
          NPM_CONFIG_PROGRESS: false
    parallelism: 1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install shellcheck
      - run: npm install
      - run: npm test
