version: 2.1

orbs:
  node: circleci/node@6.3.0
  shellcheck: circleci/shellcheck@3.2.0

workflows:
  test:
    jobs:
      - node/test:
          setup:
            - shellcheck/install:
                version: 0.9.0
            # derive cache key from package.json
            - run: cp package.json package-lock.json
          override-ci-command: rm package-lock.json && npm install && git checkout -- package.json
          matrix:
            parameters:
              version:
                - 18.0.0
                - 20.0.0
                - 22.0.0
