version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          NPM_CONFIG_COLOR: false
    parallelism: 1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install shellcheck
      - run: npm install
      - run: npm test
