version: 2.1

orbs:
  node: circleci/node@4.3.0
  shellcheck: circleci/shellcheck@2.2.4

jobs:
  test:
    executor:
      name: node/default
      tag: <<parameters.version>>
    parameters:
      version:
        type: string
    steps:
      - checkout
      - shellcheck/install
      - run: npm install
      - run: npm test

workflows:
  test:
    jobs:
      - test:
          version: 10.14.2
      - test:
          version: 12.0.0
      - test:
          version: 14.0.0
      - test:
          version: 16.0.0
